services:
  - type: web
    name: flask-audio-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python newfile.py
    plan: free
    envVars: []